{.push raises: [].}
{.experimental: "strictDefs".}
{.experimental: "strictFuncs".}
{.experimental: "views".}

import std/[sugar, unittest]
import
  ../../src/pon2/core/
    [common, field, fqdn, goal, nazopuyo, placement, popresult, puyopuyo, rule, step]
import ../../src/pon2/private/[strutils]

func mark2[F: TsuField or WaterField](
    nazo: NazoPuyo[F], plcmts: varargs[Placement]
): MarkResult =
  var nazo2 = nazo
  for i, plcmt in plcmts:
    nazo2.puyoPuyo.steps[i].optPlacement.ok plcmt

  nazo2.mark

func mark2[F: TsuField or WaterField](
    nazo: NazoPuyo[F], optPlcmts: varargs[OptPlacement]
): MarkResult =
  var nazo2 = nazo
  for i, optPlcmt in optPlcmts:
    nazo2.puyoPuyo.steps[i].optPlacement = optPlcmt

  nazo2.mark

# ------------------------------------------------
# Constructor
# ------------------------------------------------

block: # init
  let
    puyoPuyoT = PuyoPuyo[TsuField].init
    puyoPuyoW = PuyoPuyo[WaterField].init
    goal = Goal.init(Count, Colors, 10)

  check NazoPuyo[TsuField].init(puyoPuyoT, goal) ==
    NazoPuyo[TsuField](puyoPuyo: puyoPuyoT, goal: goal)
  check NazoPuyo[WaterField].init(puyoPuyoW, goal) ==
    NazoPuyo[WaterField](puyoPuyo: puyoPuyoW, goal: goal)

  check NazoPuyo[TsuField].init ==
    NazoPuyo[TsuField](puyoPuyo: PuyoPuyo[TsuField].init, goal: Goal.init)
  check NazoPuyo[WaterField].init ==
    NazoPuyo[WaterField](puyoPuyo: PuyoPuyo[WaterField].init, goal: Goal.init)

# ------------------------------------------------
# Mark
# ------------------------------------------------

block: # mark
  block: # Clear
    let nazo = parseNazoPuyo[TsuField](
      """
ぷよ全て消すべし
======
......
......
......
......
......
......
......
......
......
......
......
bb.yyy
yy.bbb
------
by|
by|"""
    ).unsafeValue

    check nazo.mark2(Left3, Down2) == Accept
    check nazo.mark2(OptPlacement.ok Left3, NonePlacement) == WrongAnswer

  block: # AccumColor
    let nazo = parseNazoPuyo[TsuField](
      """
3色消すべし
======
......
......
......
......
......
......
......
......
......
......
......
...gbr
.bgbrr
------
bg|
rg|"""
    ).unsafeValue

    check nazo.mark2(Down2, Left5) == Accept
    check nazo.mark2(Left3, Left5) == WrongAnswer

  block: # AccumColorMore
    let nazo = parseNazoPuyo[TsuField](
      """
3色以上消すべし
======
......
......
......
......
......
......
......
......
......
......
......
...gbr
.bgbrr
------
bg|
rg|"""
    ).unsafeValue

    check nazo.mark2(Down2, Left5) == Accept
    check nazo.mark2(Left3, Left5) == WrongAnswer

  block: # AccumCount
    let nazo = parseNazoPuyo[TsuField](
      """
ぷよ18個消すべし
======
......
......
......
......
......
......
......
......
..b...
..y...
ggg...
ooo...
ooobbb
------
yy|
yg|"""
    ).unsafeValue

    check nazo.mark2(Up0, Down1) == Accept
    check nazo.mark2(Right3, Down3) == WrongAnswer

  block: # AccumCountMore
    let nazo = parseNazoPuyo[TsuField](
      """
ぷよ18個以上消すべし
======
......
......
......
......
......
......
......
......
..b...
..y...
ggg...
ooo...
ooobbb
------
yy|
yg|"""
    ).unsafeValue

    check nazo.mark2(Up0, Down1) == Accept
    check nazo.mark2(Right3, Down3) == WrongAnswer

  block: # Chain
    let nazo = parseNazoPuyo[WaterField](
      """
3連鎖するべし
======
......
......
......
......
......
~~~~~~
rpor..
.pp...
..y...
..y...
..y...
......
......
......
------
ry|
rp|"""
    ).unsafeValue

    check nazo.mark2(Left2, Down1) == Accept
    check nazo.mark2(Down2, Down1) == WrongAnswer

  block: # ChainMore
    let nazo = parseNazoPuyo[WaterField](
      """
3連鎖以上するべし
======
......
......
......
......
......
~~~~~~
rpor..
.pp...
..y...
..y...
..y...
......
......
......
------
ry|
rp|"""
    ).unsafeValue

    check nazo.mark2(Left2, Down1) == Accept
    check nazo.mark2(Down2, Down1) == WrongAnswer

  block: # ClearChain
    let nazo = parseNazoPuyo[TsuField](
      """
5連鎖&ぷよ全て消すべし
======
......
......
......
......
......
......
.....r
..y..r
..yy.y
..bbby
..hooo
..ybby
..yrry
------
by|
by|
by|"""
    ).unsafeValue

    check nazo.mark2(Up1, Left2, Up4) == Accept
    check nazo.mark2(Down3, Up3, Left4) == WrongAnswer

  block: # ClearChainMore
    let nazo = parseNazoPuyo[TsuField](
      """
5連鎖以上&ぷよ全て消すべし
======
......
......
......
......
......
......
.....r
..y..r
..yy.y
..bbby
..hooo
..ybby
..yrry
------
by|
by|
by|"""
    ).unsafeValue

    check nazo.mark2(Up1, Left2, Up4) == Accept
    check nazo.mark2(Down3, Up3, Left4) == WrongAnswer

  block: # Color
    let nazo = parseNazoPuyo[TsuField](
      """
2色同時に消すべし
======
......
......
......
......
......
......
...g..
...po.
...pg.
...pg.
...og.
.o.pp.
.gggp.
------
gp|
gp|"""
    ).unsafeValue
    check nazo.mark2(Left5, Down5) == Accept
    check nazo.mark2(Down5, Up4) == WrongAnswer

  block: # ColorMore
    let nazo = parseNazoPuyo[TsuField](
      """
2色以上同時に消すべし
======
......
......
......
......
......
......
...g..
...po.
...pg.
...pg.
...og.
.o.pp.
.gggp.
------
gp|
gp|"""
    ).unsafeValue
    check nazo.mark2(Left5, Down5) == Accept
    check nazo.mark2(Down5, Up4) == WrongAnswer

  block: # Count
    let nazo = parseNazoPuyo[TsuField](
      """
ぷよ12個同時に消すべし
======
......
......
......
......
......
......
......
......
......
...r..
..rr..
rggb..
rrgbb.
------
rb|
rg|"""
    ).unsafeValue
    check nazo.mark2(Down2, Left2) == Accept
    check nazo.mark2(Down5, Down1) == WrongAnswer

  block: # CountMore
    let nazo = parseNazoPuyo[TsuField](
      """
ぷよ12個以上同時に消すべし
======
......
......
......
......
......
......
......
......
......
...r..
..rr..
rggb..
rrgbb.
------
rb|
rg|"""
    ).unsafeValue
    check nazo.mark2(Down2, Left2) == Accept
    check nazo.mark2(Down5, Down1) == WrongAnswer

  block: # Place
    let nazo = parseNazoPuyo[TsuField](
      """
ぷよ2箇所同時に消すべし
======
......
......
......
......
......
......
......
......
......
......
....r.
y...y.
yyryy.
------
ry|
ry|"""
    ).unsafeValue
    check nazo.mark2(Down3, Left2) == Accept
    check nazo.mark2(Up2, Down3) == WrongAnswer

  block: # PlaceMore
    let nazo = parseNazoPuyo[TsuField](
      """
ぷよ2箇所以上同時に消すべし
======
......
......
......
......
......
......
......
......
......
......
....r.
y...y.
yyryy.
------
ry|
ry|"""
    ).unsafeValue
    check nazo.mark2(Down3, Left2) == Accept
    check nazo.mark2(Up2, Down3) == WrongAnswer

  block: # Conn
    let nazo = parseNazoPuyo[TsuField](
      """
ぷよ7連結で消すべし
======
......
......
......
......
......
......
......
......
..o...
grgr..
ggrg..
rrbb..
gggbr.
------
gg|
bg|"""
    ).unsafeValue
    check nazo.mark2(Up3, Left4) == Accept
    check nazo.mark2(Up1, Left2) == WrongAnswer

  block: # ConnMore
    let nazo = parseNazoPuyo[TsuField](
      """
ぷよ7連結以上で消すべし
======
......
......
......
......
......
......
......
......
..o...
grgr..
ggrg..
rrbb..
gggbr.
------
gg|
bg|"""
    ).unsafeValue
    check nazo.mark2(Up3, Left4) == Accept
    check nazo.mark2(Up1, Left2) == WrongAnswer

  block: # Dead, InvalidMove, SkipMove
    let nazo = parseNazoPuyo[TsuField](
      """
ぷよ全て消すべし
======
......
.....o
.....o
..o..o
..o..o
..o..o
..o..o
..o..o
..o..o
..o..o
..o..o
..o..o
..o..o
------
rg|
by|"""
    ).unsafeValue

    check nazo.mark2(Up2) == Dead
    check nazo.mark2(Up5) == InvalidMove
    check nazo.mark2(NonePlacement, OptPlacement.ok Up3) == SkipMove

  block: # NotSupport
    let nazo = parseNazoPuyo[TsuField](
      """
おじゃまぷよ2箇所以上同時に消すべし
======
......
......
......
......
......
......
......
......
......
......
....r.
y...y.
yyryy.
------
ry|
ry|"""
    ).unsafeValue

    check nazo.mark2(NonePlacement) == NotSupport

  block: # initial nazopuyo is clear
    let nazo = parseNazoPuyo[TsuField](
      """
ぷよ全て消すべし
======
......
......
......
......
......
......
......
......
......
......
......
......
......
------
rr|"""
    ).unsafeValue

    check nazo.mark2(Down1) == WrongAnswer

  block: # zero placements
    let nazo = parseNazoPuyo[TsuField](
      """
ぷよ全て消すべし
======
......
......
......
......
......
......
......
......
......
......
......
......
rrr...
------
"""
    ).unsafeValue

    check nazo.mark2 == WrongAnswer

  block: # w/ endStepIdx
    let nazo = parseNazoPuyo[TsuField](
      """
ぷよ全て消すべし
======
......
......
......
......
......
......
......
......
......
......
......
bb.yyy
yy.bbb
------
by|43
by|3S"""
    ).unsafeValue

    check nazo.mark(-1) == Accept
    check nazo.mark(0) == WrongAnswer
    check nazo.mark(1) == WrongAnswer
    check nazo.mark(2) == Accept

# ------------------------------------------------
# Nazo Puyo <-> string
# ------------------------------------------------

block: # `$`, parseNazoPuyo
  let
    str =
      """
色ぷよ2連結以上で消すべし
======
r.....
.g....
..b...
...y..
....p.
.....o
....h.
......
......
......
......
......
......
------
by|
(0,1,0,0,0,2)
rg|23
[3,0,0,0,4,0]
pp|4N"""

    nazoPuyo = parseNazoPuyo[TsuField](str).unsafeValue

  check $nazoPuyo == str

# ------------------------------------------------
# Nazo Puyo <-> URI
# ------------------------------------------------

block: # toUriQuery, parseNazoPuyo
  block:
    let
      str =
        """
2連鎖するべし
======
......
......
......
......
......
......
......
......
......
......
.op...
...yg.
...b.r
------
by|
(0,1,0,0,0,1)
rg|23"""
      nazoPuyo = parseNazoPuyo[TsuField](str).unsafeValue

      queryPon2 = "field=t_op......yg....b.r&steps=byo0_1_0_0_0_1org23&goal=5__2"
      queryIshikawa = "6E004g031_E1ahce__u02"

    check nazoPuyo.toUriQuery(Pon2) == StrErrorResult[string].ok queryPon2
    check nazoPuyo.toUriQuery(Ishikawa) == StrErrorResult[string].ok queryIshikawa
    check nazoPuyo.toUriQuery(Ips) == StrErrorResult[string].ok queryIshikawa

    check parseNazoPuyo[TsuField](queryPon2, Pon2) ==
      StrErrorResult[NazoPuyo[TsuField]].ok nazoPuyo
    check parseNazoPuyo[TsuField](queryIshikawa, Ishikawa) ==
      StrErrorResult[NazoPuyo[TsuField]].ok nazoPuyo
    check parseNazoPuyo[TsuField](queryIshikawa, Ips) ==
      StrErrorResult[NazoPuyo[TsuField]].ok nazoPuyo

  block: # empty steps
    let
      str =
        """
赤ぷよ全て消すべし
======
......
......
......
......
......
......
......
......
......
......
......
......
g.....
------
"""
      nazoPuyo = parseNazoPuyo[TsuField](str).unsafeValue

      queryPon2 = "field=t_g.....&steps&goal=0_1_"
      queryIshikawa = "g00___210"

    check nazoPuyo.toUriQuery(Pon2) == StrErrorResult[string].ok queryPon2
    check nazoPuyo.toUriQuery(Ishikawa) == StrErrorResult[string].ok queryIshikawa
    check nazoPuyo.toUriQuery(Ips) == StrErrorResult[string].ok queryIshikawa

    check parseNazoPuyo[TsuField](queryPon2, Pon2) ==
      StrErrorResult[NazoPuyo[TsuField]].ok nazoPuyo
    check parseNazoPuyo[TsuField](queryIshikawa, Ishikawa) ==
      StrErrorResult[NazoPuyo[TsuField]].ok nazoPuyo
    check parseNazoPuyo[TsuField](queryIshikawa, Ips) ==
      StrErrorResult[NazoPuyo[TsuField]].ok nazoPuyo

  block: # empty field and steps
    let
      str =
        """
3色同時に消すべし
======
......
......
......
......
......
......
......
......
......
......
......
......
......
------
"""
      nazoPuyo = parseNazoPuyo[TsuField](str).unsafeValue

      queryPon2 = "field=t_&steps&goal=9__3"
      queryIshikawa = "___E03"

    check nazoPuyo.toUriQuery(Pon2) == StrErrorResult[string].ok queryPon2
    check nazoPuyo.toUriQuery(Ishikawa) == StrErrorResult[string].ok queryIshikawa
    check nazoPuyo.toUriQuery(Ips) == StrErrorResult[string].ok queryIshikawa

    check parseNazoPuyo[TsuField](queryPon2, Pon2) ==
      StrErrorResult[NazoPuyo[TsuField]].ok nazoPuyo
    check parseNazoPuyo[TsuField](queryIshikawa, Ishikawa) ==
      StrErrorResult[NazoPuyo[TsuField]].ok nazoPuyo
    check parseNazoPuyo[TsuField](queryIshikawa, Ips) ==
      StrErrorResult[NazoPuyo[TsuField]].ok nazoPuyo

  block: # empty query
    let
      str =
        """
ぷよ全て消すべし
======
......
......
......
......
......
......
......
......
......
......
......
......
......
------
"""
      nazoPuyo = parseNazoPuyo[TsuField](str).unsafeValue

      queryPon2 = "field=t_&steps&goal=0_0_"
      queryPon22 = "field=t_&steps&goal="
      queryPon23 = "field=t_&steps"

    check nazoPuyo.toUriQuery(Pon2) == StrErrorResult[string].ok queryPon2

    for query in [queryPon2, queryPon22, queryPon23]:
      check parseNazoPuyo[TsuField](query, Pon2) ==
        StrErrorResult[NazoPuyo[TsuField]].ok nazoPuyo
