#[
autogenerated by docgen
loc: /home/runner/work/pon2/pon2/src/pon2/private/macros.nim(150, 3)
rdoccmd: 
]#
import std/assertions
import "/home/runner/work/pon2/pon2/src/pon2/private/macros.nim"
{.line: ("/home/runner/work/pon2/pon2/src/pon2/private/macros.nim", 150, 3).}:
  type MyEnum = enum
    Foo
    Bar

  const x = Foo
  staticCase:
    case x
    of Foo:
      assert x == Foo
    of Bar:
      assert x == Bar

