#[
autogenerated by docgen
loc: /home/izumiya/tmp/hogehoge/pon2/src/pon2/private/app/generate.nim(32, 3)
rdoccmd: 
]#
import std/assertions
import "/home/izumiya/tmp/hogehoge/pon2/src/pon2/private/app/generate.nim"
{.line: ("/home/izumiya/tmp/hogehoge/pon2/src/pon2/private/app/generate.nim", 32, 3).}:
  import std/[math, random, sequtils]

  var rng = 123.initRand
  let numbers = rng.split(10, 3, false)
  assert numbers.sum == 10
  assert numbers.len == 3
  assert numbers.allIt it > 0

