# autogenerated by docgen
# source: /home/izumiya/tmp/hogehoge/pon2/src/pon2/private/app/generate.nim
# rdoccmd: 
import "/home/izumiya/tmp/hogehoge/pon2/www/docs/web/nimcache/runnableExamples/generate_examples_1.nim"
import "/home/izumiya/tmp/hogehoge/pon2/www/docs/web/nimcache/runnableExamples/generate_examples_2.nim"
