#[
autogenerated by docgen
loc: /home/runner/work/pon2/pon2/src/pon2/private/macros.nim(45, 3)
rdoccmd: 
]#
import std/assertions
import "/home/runner/work/pon2/pon2/src/pon2/private/macros.nim"
{.line: ("/home/runner/work/pon2/pon2/src/pon2/private/macros.nim", 45, 3).}:
  # You can define a new macro `defineExample` by
  # `defineExpand("Example", "Foo", "Bar")`.
  # This defines the following macro:
  macro expandExample(identsAndBody: varargs[untyped]): untyped =
    ## Runs in sequence with the body (the last argument) changed to the specified
    ## identifiers (the rest arguments) with the suffix Foo, Bar.
    ## Underscore in the body is replaced by the index of the suffix.
    let
      body = identsAndBody[^1]
      idents = identsAndBody[0 ..^ 2]
      stmts = nnkStmtList.newNimNode body

    var bodyFoo = body.replaced("_".ident, 0.newLit)
    for id in idents:
      bodyFoo.replace id, (id.strVal & "Foo").ident

    add(stmts, bodyFoo)

    var bodyBar = body.replaced("_".ident, 1.newLit)
    for id in idents:
      bodyBar.replace id, (id.strVal & "Bar").ident

    add(stmts, bodyBar)

    stmts

  # Usage of `expandExample`:
  let
    xFoo = 10
    xBar = 20
    yFoo = 100
    yBar = 200

  expandExample x, y:
    assert x == _.succ * 10
    assert y == _.succ * 100

