# autogenerated by docgen
# source: /home/runner/work/pon2/pon2/src/pon2/private/macros.nim
# rdoccmd: 
import "/home/runner/work/pon2/pon2/pages/docs/api/js/nimcache/runnableExamples/macros_examples_1.nim"
import "/home/runner/work/pon2/pon2/pages/docs/api/js/nimcache/runnableExamples/macros_examples_2.nim"
