/* Generated by the Nim Compiler v2.2.4 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI721420291 = {size: 0,kind: 44,base: null,node: null,finalizer: null};
var NTI721420292 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NNI721420292 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a0", len: 0, typ: NTI721420291, name: "a0", sons: null}, 
{kind: 1, offset: "a1", len: 0, typ: NTI721420291, name: "a1", sons: null}]};
NTI721420292.node = NNI721420292;
var DefaultRandSeed_721420302 = {a0: 7616934476015405061n, a1: 15122295919272093642n};

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_p0, src_p1, ti_p2) {
  var result_33557330 = null;

    switch (ti_p2.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer__system_u2878(ti_p2))) {
      result_33557330 = src_p1;
      }
      else {
        result_33557330 = [src_p1[0], src_p1[1]];
      }
      
      break;
    case 19:
            if (dest_p0 === null || dest_p0 === undefined) {
        dest_p0 = {};
      }
      else {
        for (var key in dest_p0) { delete dest_p0[key]; }
      }
      for (var key in src_p1) { dest_p0[key] = src_p1[key]; }
      result_33557330 = dest_p0;
    
      break;
    case 18:
    case 17:
      if (!((ti_p2.base == null))) {
      result_33557330 = nimCopy(dest_p0, src_p1, ti_p2.base);
      }
      else {
      if ((ti_p2.kind == 17)) {
      result_33557330 = (dest_p0 === null || dest_p0 === undefined) ? {m_type: ti_p2} : dest_p0;
      }
      else {
        result_33557330 = (dest_p0 === null || dest_p0 === undefined) ? {} : dest_p0;
      }
      }
      nimCopyAux(result_33557330, src_p1, ti_p2.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_p1)) { 
        if(dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new src_p1.constructor(src_p1);
        } else {
          dest_p0.set(src_p1, 0);
        }
        result_33557330 = dest_p0;
      } else {
        if (src_p1 === null) {
          result_33557330 = null;
        }
        else {
          if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
            dest_p0 = new Array(src_p1.length);
          }
          result_33557330 = dest_p0;
          for (var i = 0; i < src_p1.length; ++i) {
            result_33557330[i] = nimCopy(result_33557330[i], src_p1[i], ti_p2.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_p1 === null) {
        result_33557330 = null;
      }
      else {
        if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new Array(src_p1.length);
        }
        result_33557330 = dest_p0;
        for (var i = 0; i < src_p1.length; ++i) {
          result_33557330[i] = nimCopy(result_33557330[i], src_p1[i], ti_p2.base);
        }
      }
    
      break;
    case 28:
            if (src_p1 !== null) {
        result_33557330 = src_p1.slice(0);
      }
    
      break;
    default: 
      result_33557330 = src_p1;
      break;
    }

  return result_33557330;

}
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module options", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module options", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/options.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/js/jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/js/jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module times", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/times.nim", line: 0};
framePtr = F;
F.line = 1373;
F.filename = "times.nim";
if (globalThis.utcInstance_872417025 === undefined) {
  globalThis.utcInstance_872417025 = [null];
}
F.line = 1374;
if (globalThis.localInstance_872417026 === undefined) {
  globalThis.localInstance_872417026 = [null];
}
framePtr = F.prev;
var F = {procname: "module times", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/times.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function isFatPointer__system_u2878(ti_p0) {
  var result_33557312 = false;

  BeforeRet: {
    result_33557312 = !((ConstSet1[ti_p0.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557312;

}

function nimCopyAux(dest_p0, src_p1, n_p2) {
    switch (n_p2.kind) {
    case 0:
      break;
    case 1:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_p2.sons.length; i++) {
      nimCopyAux(dest_p0, src_p1, n_p2.sons[i]);
    }
    
      break;
    case 3:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
      for (var i = 0; i < n_p2.sons.length; ++i) {
        nimCopyAux(dest_p0, src_p1, n_p2.sons[i][1]);
      }
    
      break;
    }

  
}
var F = {procname: "module random", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/random.nim", line: 0};
framePtr = F;
F.line = 116;
F.filename = "random.nim";
var state_721420303 = [nimCopy(null, DefaultRandSeed_721420302, NTI721420292)];
framePtr = F.prev;
var F = {procname: "module random", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/random.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module sequtils", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/collections/sequtils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module sequtils", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/collections/sequtils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module underscored_calls", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/std/private/underscored_calls.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module underscored_calls", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/std/private/underscored_calls.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module sugar", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/sugar.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module sugar", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/sugar.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strformat", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/strformat.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strformat", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/strformat.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module results", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/results-0.5.1-a9c011f74bc9ed5c91103917b9f382b12e82a9e7/results.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module results", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/results-0.5.1-a9c011f74bc9ed5c91103917b9f382b12e82a9e7/results.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module results2", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/results2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module results2", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/results2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module hashes", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/hashes.nim", line: 0};
framePtr = F;
F.line = 219;
F.filename = "hashes.nim";
var objectID_1241514162 = [0];
framePtr = F.prev;
var F = {procname: "module hashes", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/hashes.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module outparams", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/std/outparams.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module outparams", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/std/outparams.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/collections/tables.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/collections/tables.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables2", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/tables2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables2", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/tables2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module cell", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/cell.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module cell", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/cell.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module common", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/common.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module common", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/common.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fqdn", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/fqdn.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fqdn", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/fqdn.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module rule", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/rule.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module rule", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/rule.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module assign3", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/assign3.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module assign3", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/assign3.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module notice", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/notice.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module notice", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/notice.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module arrayops2", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/arrayops2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module arrayops2", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/arrayops2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module staticfor", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/stew-0.4.2-928e82cb8d2f554e8f10feb2349ee9c32fee3a8c/stew/staticfor.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module staticfor", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/stew-0.4.2-928e82cb8d2f554e8f10feb2349ee9c32fee3a8c/stew/staticfor.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module staticfor2", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/staticfor2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module staticfor2", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/staticfor2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math2", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/math2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math2", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/math2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module moveresult", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/moveresult.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module moveresult", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/moveresult.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module pair", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/pair.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module pair", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/pair.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils2", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/strutils2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils2", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/strutils2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros2", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/macros2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros2", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/macros2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module placement", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/placement.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module placement", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/placement.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unionfind", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/unionfind.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unionfind", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/unionfind.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module setutils", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/std/setutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module setutils", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/std/setutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module simd", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/simd.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module simd", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/simd.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module endians2", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/stew-0.4.2-928e82cb8d2f554e8f10feb2349ee9c32fee3a8c/stew/endians2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module endians2", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/stew-0.4.2-928e82cb8d2f554e8f10feb2349ee9c32fee3a8c/stew/endians2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops2", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/stew-0.4.2-928e82cb8d2f554e8f10feb2349ee9c32fee3a8c/stew/bitops2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops2", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/stew-0.4.2-928e82cb8d2f554e8f10feb2349ee9c32fee3a8c/stew/bitops2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops3", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/bitops3.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops3", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/bitops3.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bit32", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/core/binfield/bit32.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bit32", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/core/binfield/bit32.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module binfield", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/core/binfield.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module binfield", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/core/binfield.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module popresult", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/popresult.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module popresult", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/popresult.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module deques", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/collections/deques.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module deques", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/collections/deques.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module deques2", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/deques2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module deques2", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/deques2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module step", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/step.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module step", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/step.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module field", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/field.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module field", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/field.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module goal", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/goal.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module goal", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/goal.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module base64", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/base64.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module base64", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/base64.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module decode_helpers", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/std/private/decode_helpers.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module decode_helpers", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/std/private/decode_helpers.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module uri", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/uri.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module uri", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/uri.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module puyopuyo", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/puyopuyo.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module puyopuyo", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/puyopuyo.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module nazopuyo", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/core/nazopuyo.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module nazopuyo", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/core/nazopuyo.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module nazopuyo", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/nazopuyo.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module nazopuyo", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core/nazopuyo.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module core", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module core", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/core.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module nazopuyowrap", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/app/nazopuyowrap.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module nazopuyowrap", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/app/nazopuyowrap.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module core", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/core.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module core", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/core.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsffi", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/js/jsffi.nim", line: 0};
framePtr = F;
F.line = 45;
F.filename = "jsffi.nim";
F.line = 46;
framePtr = F.prev;
var F = {procname: "module jsffi", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/js/jsffi.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/js/asyncjs.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/js/asyncjs.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module dom", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/js/dom.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module dom", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/js/dom.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsre", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/js/jsre.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsre", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/js/jsre.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module utils", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module utils", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module webworker", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/webworker.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module webworker", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/webworker.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module solve", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/app/solve.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module solve", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/app/solve.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module generate", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/app/generate.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module generate", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/app/generate.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module key", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/app/key.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module key", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/app/key.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module permute", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/app/permute.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module permute", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/app/permute.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module simulator", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/app/simulator.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module simulator", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/app/simulator.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module ide", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/app/ide.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module ide", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/app/ide.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module critbits", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/collections/critbits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module critbits", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/pure/collections/critbits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module critbits2", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/critbits2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module critbits2", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/critbits2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module marathon", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/app/marathon.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module marathon", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/app/marathon.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module app", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/app.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module app", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/app.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module kdom", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/karax-1.5.0-58dfc7a459d631d0416b3dd43609ce6bc4b96c92/karax/kdom.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module kdom", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/karax-1.5.0-58dfc7a459d631d0416b3dd43609ce6bc4b96c92/karax/kdom.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module kbase", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/karax-1.5.0-58dfc7a459d631d0416b3dd43609ce6bc4b96c92/karax/kbase.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module kbase", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/karax-1.5.0-58dfc7a459d631d0416b3dd43609ce6bc4b96c92/karax/kbase.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jdict", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/karax-1.5.0-58dfc7a459d631d0416b3dd43609ce6bc4b96c92/karax/jdict.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jdict", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/karax-1.5.0-58dfc7a459d631d0416b3dd43609ce6bc4b96c92/karax/jdict.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jstrutils", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/karax-1.5.0-58dfc7a459d631d0416b3dd43609ce6bc4b96c92/karax/jstrutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jstrutils", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/karax-1.5.0-58dfc7a459d631d0416b3dd43609ce6bc4b96c92/karax/jstrutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module vstyles", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/karax-1.5.0-58dfc7a459d631d0416b3dd43609ce6bc4b96c92/karax/vstyles.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module vstyles", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/karax-1.5.0-58dfc7a459d631d0416b3dd43609ce6bc4b96c92/karax/vstyles.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module vdom", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/karax-1.5.0-58dfc7a459d631d0416b3dd43609ce6bc4b96c92/karax/vdom.nim", line: 0};
framePtr = F;
F.line = 75;
F.filename = "vdom.nim";
var svgNamespace_2164261090 = [[104,116,116,112,58,47,47,119,119,119,46,119,51,46,111,114,103,47,50,48,48,48,47,115,118,103]];
F.line = 76;
var mathNamespace_2164261091 = [[104,116,116,112,58,47,47,119,119,119,46,119,51,46,111,114,103,47,49,57,57,56,47,77,97,116,104,47,77,97,116,104,77,76]];
F.line = 262;
var gid_2164261604 = [0];
framePtr = F.prev;
var F = {procname: "module vdom", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/karax-1.5.0-58dfc7a459d631d0416b3dd43609ce6bc4b96c92/karax/vdom.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module compact", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/karax-1.5.0-58dfc7a459d631d0416b3dd43609ce6bc4b96c92/karax/compact.nim", line: 0};
framePtr = F;
F.line = 10;
F.filename = "compact.nim";
var vcomponents_2181038102 = [{}];
F.line = 22;
framePtr = F.prev;
var F = {procname: "module compact", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/karax-1.5.0-58dfc7a459d631d0416b3dd43609ce6bc4b96c92/karax/compact.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module karax", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/karax-1.5.0-58dfc7a459d631d0416b3dd43609ce6bc4b96c92/karax/karax.nim", line: 0};
framePtr = F;
F.line = 60;
F.filename = "karax.nim";
var kxi__ = null;
framePtr = F.prev;
var F = {procname: "module karax", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/karax-1.5.0-58dfc7a459d631d0416b3dd43609ce6bc4b96c92/karax/karax.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module karaxdsl", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/karax-1.5.0-58dfc7a459d631d0416b3dd43609ce6bc4b96c92/karax/karaxdsl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module karaxdsl", prev: framePtr, filename: "/home/izumiya/.nimble/pkgs2/karax-1.5.0-58dfc7a459d631d0416b3dd43609ce6bc4b96c92/karax/karaxdsl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module setting", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/ide/setting.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module setting", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/ide/setting.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module simulator", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/gui/simulator.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module simulator", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/private/gui/simulator.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module ctrl", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/ide/ctrl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module ctrl", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/ide/ctrl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module pagination", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/ide/pagination.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module pagination", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/ide/pagination.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module ctrl", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator/ctrl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module ctrl", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator/ctrl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module color", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/color.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module color", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/color.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module field", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator/field.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module field", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator/field.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module goal", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator/goal.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module goal", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator/goal.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module msg", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator/msg.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module msg", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator/msg.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module next", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator/next.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module next", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator/next.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module operating", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator/operating.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module operating", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator/operating.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module palette", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator/palette.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module palette", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator/palette.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module setting", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator/setting.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module setting", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator/setting.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/izumiya/.choosenim/toolchains/nim-2.2.4/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module share", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator/share.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module share", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator/share.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module step", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator/step.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module step", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator/step.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module simulator", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator/simulator.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module simulator", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator/simulator.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module simulator", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module simulator", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/simulator.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module ide", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/ide/ide.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module ide", prev: framePtr, filename: "/home/izumiya/pon2/src/pon2/gui/ide/ide.nim", line: 0};
framePtr = F;
framePtr = F.prev;
