#[
autogenerated by docgen
loc: /home/izumiya/tmp/hogehoge/pon2/src/pon2/private/app/generate.nim(91, 3)
rdoccmd: 
]#
import std/assertions
import "/home/izumiya/tmp/hogehoge/pon2/src/pon2/private/app/generate.nim"
{.line: ("/home/izumiya/tmp/hogehoge/pon2/src/pon2/private/app/generate.nim", 91, 3).}:
  import std/[options, random]

  var rng = 123.initRand
  let numbers = rng.split(10, [some Natural 2, some Natural 3])
  assert numbers == @[4, 6]

