name: Run Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
        if: runner.os != 'Windows'

      - uses: jiro4989/setup-nim-action@v1

      - run: >-
          nimble -y install
          docopt karax nigui tiny_sqlite yaml
          https://github.com/izumiya-keisuke/puyo-core
          https://github.com/izumiya-keisuke/nazopuyo-core

      - run: nim c -r ./tests/makeTest.nim
        if: runner.os == 'Linux'

      - run: nim c -r -d:avx2=false ./tests/makeTest.nim
        if: runner.os == 'Windows'

      - run: nim c -r -d:bmi2=false -d:avx2=false ./tests/makeTest.nim
        if: runner.os == 'macOS'

      - run: nimble -y test